#!/bin/bash

# Install into git hooks folder with the following command
# ln -s `pwd`/pre-commit ../.git/hooks/pre-commit
#
# This is to automaticaly create tag if a new version is added at the top
# Format of the tag is v.<version>
# The first line of notes.md is parsed based on the following pattern
# `<version>` the rest
#
# .git/config is recommended as ameneded to push local tags with git push
# [remote "origin"]
#         url = ...
#         fetch = ...
#         push = +refs/heads/*
#         push = +refs/tags/*


LINE=$(head -n 1 notes.md)
echo "line: $LINE"
REGEX='`(.*)`.*'
if [[ $LINE =~ $REGEX ]] 
then 
   VERSION=${BASH_REMATCH[1]}  
   echo "VERSION $VERSION"
   TAG="v.$VERSION"
   if ! git rev-parse $TAG >/dev/null 2>&1
   then
       echo "tag not found"
       git tag $TAG
   else
       echo "tag found"
   fi
fi


