/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gitHubActions;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

public class App {

    private static final Logger log = LogManager.getLogger();

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        log.info("This is a test logger");
        System.out.println(log.getClass().getName());
    }
}
