name: learn-github-actions
on: [push]
jobs:
  auto-report:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create report file
        run: date +%s > report.txt
      - name: Commit report
        run: |
          git config --global user.name 'AutoBuildDZSomething'
          git config --global user.email 'auto-build-dz-something@users.noreply.github.com'
          git add report.txt
          git commit -am "Automated report"
          git push
  output-something:
    runs-on: ubuntu-latest
    name: Save output
    steps:
      - shell: bash
        run: |
          expr 1 + 1 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v1
        with:
          name: output-log-file
          path: output.log
